"""empty message

Revision ID: 36a8d9c7a720
Revises: 9f84624508af
Create Date: 2025-05-29 10:08:38.285888

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36a8d9c7a720'
down_revision: Union[str, None] = '9f84624508af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('phone', 'processor',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('phone', 'processor',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
